Circleci Submodules setup
Medology/submodules pull request #118
Opened 2022-04-05 16:25 UTC by Vagoasdf

For: Medology/Umami#something

BUG FIX:

**Cause:**

**Solution:**

FEATURE IMPLEMENTATION:

Whatever you want (screenshots, etc)

2022-04-05 17:46 UTC, Chekote requested changes

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +      image: ubuntu-2004:202010-01
Please use the latest image. You can get a list of images [here](https://circleci.com/docs/2.0/configuration-reference/#machine).

```suggestion
      image: ubuntu-2004:202111-02 
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +    working_directory: /tmp/stdcheck.com
We should use a working directory that is more appropriate for this project.

```suggestion
    working_directory: /tmp/submodules
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +            git config --global --add url.git@github.com:.insteadOf https://github.com/
Please add a command to use the `circleci.git.configure` function from Submodules:

```
  ##################
  # Git commands.
  ##################
  git_configure:
    steps:
      - run:
          name: Configure Git
          command: |
            . submodules/lib/circleci.bash
            circleci.git.configure
```

Then invoke that:

```suggestion
      - git_configure
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +          key: v1-yarn-{{ checksum "yarn.lock" }}
This seems like a strange thing to be part of the `pull-merge` command. It doesn't seem related. I feel it should be elsewhere.

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +  circleci_configure_path:
Let's consistently give these sections headings.

```suggestion
  ##################
  # CircleCI commands
  ##################
  circleci_configure_path:
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +  gcloud_configure:
```suggestion
  ##################
  # GCloud commands
  ##################
  gcloud_configure:
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +
One blank line for separation is fine.

```suggestion
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +  ex-machina:
Let's give the executor a more sensible name:

```suggestion
  ubuntu:
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +    executor: ex-machina
```suggestion
    executor: ubuntu
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +          command: init_submodules_project
Is there a reason that we can't use the same convention as the other projects and call this just `init_project`?

```suggestion
          command: init_project
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +          command: bats -pr --report-formatter junit  tests_bash
Unnecessary additional whitespace here.

```suggestion
          command: bats -pr --report-formatter junit tests_bash
```

2022-04-05 17:46 UTC, Chekote commented on .circleci/config.yml
> +            - STDcheck Github Triage Authorization
The CircleCI contexts naming convention implies what their appropriate usage is. If the name is not prefixed with a specific project name, such as `Docker Hub Read-Only`, then it is appropriate to use it in any project. However, if it *is* prefixed with a project name, such as `STDcheck Github Triage Authorization`, then the context is specifically for that project (STDcheck in this place). You should not use project specific contexts in the wrong project because it will inappropriately grant the Submodules workflow access to STDcheck's resources.

If there is not an appropriate context for you to use, then we will need to create a new one specifically for Submodules.

2022-04-05 17:46 UTC, Chekote commented on README.md
> +![STDcheck](https://www.stdcheck.com/images/logo%402x.png)
This logo isn't appropriate for this project.

2022-04-05 17:46 UTC, Chekote commented on README.md
> +The project uses BATS for automated bash testing using.You can execute your BATS tests as follows:
```suggestion
The project uses BATS for automated bash testing using. You can execute your BATS tests as follows:
```

2022-04-05 17:46 UTC, Chekote commented on bin/ci-style-fixer
> -
Why were these lines removed?

2022-04-05 17:46 UTC, Chekote commented on bin/init_submodules_project
> +. bin/init/init_git_hooks.sh
Please add a line break to the end of the file.

2022-04-05 17:46 UTC, Chekote commented on bin/pre-commit
> -
Please restore this blank line. Code blocks (curly braces) should always have a blank line separating them from the next line of code.

2022-04-05 17:46 UTC, Chekote commented on bin/prettier-eslint
> +then
Let's keep the if and then on the same line:

```suggestion
if [ $GIT_SUBMODULE_REMOTE = $CURRENT_REMOTE ]; then
```

Let's also double-quote these values to avoid globbing and word-splitting:

```suggestion
if [ "$GIT_SUBMODULE_REMOTE" = "$CURRENT_REMOTE" ]; then
```

2022-04-05 17:46 UTC, Chekote commented on bin/prettier-eslint
> +fi
This should not be necessary, the `git.paths.get` provides two variables: "ROOT" and "SUBMODULES".

When you are using the Submodules repo as a Git submodule (e.g. in STDcheck), then ROOT will be the host project dir, and SUBMODULES will be the submodules dir.

If you are running Submodules as a standalone project (such as you are doing in CI here), then both ROOT and SUBMODULES will be the submodules dir, because submodules *is* the root.

This means that if you always want to load `docker.bash` from submodules, you can simply use `$SUBMODULES` and not `$ROOT`:

```suggestion
. "$SUBMODULES/lib/docker.bash"
```

2022-04-05 17:46 UTC, Chekote commented on testingFixer/example.js
> +Tester(message)
Did you mean to commit this file?

2022-04-05 22:54 UTC, Vagoasdf commented on .circleci/config.yml
> +          key: v1-yarn-{{ checksum "yarn.lock" }}
Im double checking, not sure we are even going to use cache if  there is nothing like yarn or composer here

2022-04-05 22:57 UTC, Vagoasdf commented on testingFixer/example.js
> +Tester(message)
This file its being used to test the ci-style-fixer. Its going to be deleted before merging

2022-04-05 23:00 UTC, Vagoasdf commented on .circleci/config.yml
> +          command: init_submodules_project
Since in the other projects, both `bin` and `submodules/bin` is added to PATH, i'm concerned that if we call it init_project it might cause a conflict, since there would be a `bin/init_project `and a `submodules/bin/init_project`, thats it two init_project in PATH

2022-04-05 23:14 UTC, Vagoasdf commented on bin/ci-style-fixer
> -
By Mistake. Added two echos to check if the checkout was killing the workflow. Removed the echos and didn't realized there was a separation before

2022-04-05 23:15 UTC, Vagoasdf commented on bin/pre-commit
> -
The more you Know

2022-04-07 17:20 UTC, Chekote requested changes
Almost good. Just one new minor issue, and updates to two existing conversations:

1. https://github.com/Medology/submodules/pull/118#discussion_r843093159
2. https://github.com/Medology/submodules/pull/118#discussion_r843096488

2022-04-07 17:20 UTC, Chekote commented on .circleci/config.yml
> +    description: Fix for CI prefi xing the PATH if you set it via env vars. DO NOT DO THAT. See commit description or details.
Looks like you made an accidental edit here.

```suggestion
    description: Fix for CI prefixing the PATH if you set it via env vars. DO NOT DO THAT. See commit description or details.
```

2022-04-08 19:35 UTC, Chekote approved these changes

2022-04-08 19:48 UTC, merged