Error handling on merge freeze
Medology/submodules pull request #124
Opened 2022-04-11 19:52 UTC by Vagoasdf

For: Medology/Umami#465

FEATURE IMPLEMENTATION:

Adding error Handling for when mergefreezes fails at freezing on the No promote Workflows

The library now will check for the HTTP Code during freeze, if it's not 2xx, it will halt the workflow

2022-04-12 13:04 UTC, Chekote requested changes

2022-04-12 13:04 UTC, Chekote commented on lib/mergefreeze.bash
> +    local httpCode=$1
```suggestion
    local httpCode="$1"
```

2022-04-12 13:04 UTC, Chekote commented on lib/mergefreeze.bash
> +    echo "$httpCode"
Is this a debug statement? Should it be removed?

2022-04-12 13:04 UTC, Chekote commented on lib/mergefreeze.bash
> +      echo "Unknow Error"
```suggestion
      echo "Unknow Error. HTTP response code: $httpCode"
```

2022-04-12 13:04 UTC, Chekote commented on lib/mergefreeze.bash
> +mergefreeze.describeFailure(){
Given the codes that this function understands, and the minimal information that it is presenting when it finds one it understands, I do not believe this is offering much value. Our developers should understand what HTTP response codes are, so simply outputting the received error code without using a function to say what the code means seems like it should be sufficient.

2022-04-12 14:33 UTC, Chekote commented on lib/circleci.bash
> +      fi
Yes, let's do that. Since a successful Merge Freeze would post a Slack message to `#devchat`, we should post one if the Merge Freeze fails.

2022-04-12 23:01 UTC, Vagoasdf commented on lib/circleci.bash
> +      fi
The message PR is up at https://github.com/Medology/stdcheck.com/pull/15407. it would need this PR first, so the fail state reaches the slack orb

2022-04-13 12:45 UTC, Chekote requested changes
Looking good. Just two minor changes then this is good to go.

2022-04-13 12:45 UTC, Chekote commented on lib/circleci.bash
> +        ## Enviar un mensaje de error en Slack
English please.

2022-04-13 12:45 UTC, Chekote commented on lib/mergefreeze.bash
>  }
No blank lines at the end of a function.
One blank line before return statements.

```suggestion
  fi

  return $isTwoHundred
}
```

2022-04-13 13:40 UTC, Vagoasdf commented on lib/circleci.bash
> +        ## Enviar un mensaje de error en Slack
😆  That one slipped under my radar

2022-04-13 14:43 UTC, Chekote requested changes

2022-04-13 14:43 UTC, Chekote commented on lib/circleci.bash
> +        ##By halting on stdcheck, it should send
We shouldn't mention a specific project in Submodules. The Submodules project is supposed to be agnostic.

Also, I don't really understand what you are trying to convey with this comment.

2022-04-13 15:35 UTC, Vagoasdf commented on lib/circleci.bash
> +        ##By halting on stdcheck, it should send
It was supposed to be deleted. Let me check if i haven't pushed the latest commit

2022-04-13 19:04 UTC, Chekote approved these changes

2022-04-13 19:21 UTC, merged