Error handling on merge freeze
Medology/submodules pull request #127
Opened 2022-04-19 19:24 UTC by Vagoasdf

For: Medology/Umami#465

FEATURE IMPLEMENTATION:

Moving the slack message template from stdcheck.com to submodules

2022-04-19 19:26 UTC, Vagoasdf commented on lib/circleci.bash
> -        circleci.job.halt
I dont know why it's taking some of these as changes. The [last commit](https://github.com/Medology/submodules/commit/9a42fbb340d1d5647eb9db52a7d0964f5a04bd87) included these

2022-04-19 19:47 UTC, Chekote commented on lib/circleci.bash
> -        circleci.job.halt
It seems like you have opened a PR from a stale version of master. Normally you should not rebase if a code review has begun, but in this case, we can make an exception. Please do the following:

* Make sure that your local master is up to date with the upstream master
* Rebase this branch onto  master
* Force push to this branch

If you do this, you should end up with a single commit [Adding the template and messages of the mergefreeze to submodules](https://github.com/Medology/submodules/pull/127/commits/675ba24e323e7f89959eb798676beb107f18b508) in this PR.

2022-04-19 20:33 UTC, Chekote requested changes

2022-04-19 20:33 UTC, Chekote commented on lib/mergefreeze.bash
> +
Please remove this unnecessary whitespace. The blank line should be here, but it should be just a `\n` character, not actual spaces.

2022-04-19 20:33 UTC, Chekote commented on bin/circleci/build_mergefreezefail_template.sh
> +#!/usr/bin/env bash
Please use `*.bash` for Bash files.

2022-04-19 20:33 UTC, Chekote commented on bin/circleci/build_mergefreezefail_template.sh
> +echo "export SLACK_TEMPLATE='$(cat "$SUBMODULES/artifacts/slack_deploy_fail_template.json" | sed -e "$regex")'" >> $BASH_ENV
Please add a new line to the end of this file.

2022-04-19 20:33 UTC, Chekote commented on bin/circleci/build_mergefreezefail_template.sh
> +echo "export SLACK_TEMPLATE='$(cat "$SUBMODULES/artifacts/slack_deploy_fail_template.json" | sed -e "$regex")'" >> $BASH_ENV
You are referencing a non-existing `$regex` var here.

2022-04-19 20:33 UTC, Chekote commented on artifacts/slack_mergefreeze_fail_template.json
> +          "text": "@channel  $CIRCLE_USERNAME attempted to freeze the *Project*: \n $CIRCLE_PROJECT_REPONAME"
```suggestion
          "text": "@channel $CIRCLE_USERNAME attempted to freeze the *Project*:\n $CIRCLE_PROJECT_REPONAME"
```

2022-04-19 22:24 UTC, Vagoasdf commented on bin/circleci/build_mergefreezefail_template.sh
> +#!/usr/bin/env bash
You mean renaming it to (...)template.bash? 

It would look odd. The other files on the bin folder, including the template for the deploy fail use `.sh`.

100% Sure?

2022-04-20 17:09 UTC, Chekote commented on bin/circleci/build_mergefreezefail_template.sh
> +#!/usr/bin/env bash
Yes, 100% sure. We just haven't gone back and proactively updated all the file extensions of the existing scripts yet.

2022-04-20 17:11 UTC, Chekote requested changes
Just one additional thing I didn't catch on my first review, and the remaining `*.bash` comment from the previous review.

2022-04-20 17:25 UTC, Vagoasdf commented on bin/circleci/build_mergefreezefail_template.sh
> +echo "export SLACK_TEMPLATE='$(cat "$SUBMODULES/artifacts/slack_deploy_fail_template.json")'" >> $BASH_ENV
🤦🏽  yes. Sorry, fixing that

2022-04-21 14:09 UTC, Chekote approved these changes

2022-04-21 14:40 UTC, merged