Stop attempt to fix non fixable files
Medology/submodules pull request #33
Opened 2020-10-02 16:33 UTC by manuerumx

For #32 

**Method:**
Add PR adding a document like a PDF file 

**Expected Behavior:**
The CI build should pass.

**Actual Result:**
The CI fails on the cs-style-fixer step.

**Cause:**
The local method uses a pre-commit hook and validates all the changes in the PR.
The CI method also generates a PR in case fixes can be applied.

The CI script attempts to fix all the files in the PR. A PDF and many other documents are not _fixable_, the hook include that validation.

**Solution:**
Filter the fixable files before attempting to fix it.

**Customer Impact (for #releasenotes):**
N/A

**QA Notes (How to set up system for manual testing)**
N/A

2020-10-02 16:46 UTC, BKorenek requested changes

2020-10-02 16:46 UTC, BKorenek commented on bin/ci-style-fixer
> +# Filter fixable files
```suggestion
# Filter fixable files
# Arguments:
#   1 the files to filter
```

2020-10-02 16:46 UTC, BKorenek commented on bin/ci-style-fixer
> +# Filter fixable files
better yet though, how do you feel about just removing the files variable from the top, and instead setting that in the method and just returning files instead?

2020-10-02 19:20 UTC, rashidsaf approved these changes

2020-10-05 12:30 UTC, BKorenek approved these changes

2020-10-05 18:44 UTC, merged