Adjust logic to also fix TypeScript files
Medology/submodules pull request #39
Opened 2020-10-14 17:03 UTC by aserv92

**Method:**
Run style fixer

**Expected Behavior:**
TS files should also be fixed

**Actual Result:**
TS files are not touched by style fixer

**Cause:**
TS files are not listed in command sent to eslint

**Solution:**
Add ts files extension front end extensions
Add ts to style fixer extensions.

2020-10-14 17:08 UTC, aserv92 commented on bin/style-fixer
> +  match="${match#*.}"
Files named like `someClass.component.ts` were causing the match logic to try to match `component.ts` to `ts`.
This change fixes the match logic so it will match `ts` to `ts` for a file named like `someClass.component.ts`

2020-10-14 17:11 UTC, manuerumx requested changes
Can you also add the `ts` extension to the file https://github.com/Medology/submodules/blob/master/bin/ci-style-fixer#L85

This is because we fix a bug where the ci-style-fixer fails when the pr includes only non-fixable files.  See the issue: https://github.com/Medology/submodules/issues/30

2020-10-14 18:22 UTC, aserv92 commented
> Can you also add the `ts` extension to the file https://github.com/Medology/submodules/blob/master/bin/ci-style-fixer#L85
> 
> This is because we fix a bug where the ci-style-fixer fails when the pr includes only non-fixable files. See the issue: #30
@manuerumx 
Good Catch, Thank you!

2020-10-14 18:32 UTC, manuerumx approved these changes

2020-10-14 21:55 UTC, rashidsaf approved these changes

2020-10-15 15:10 UTC, BKorenek commented on bin/style-fixer
> +    front_end_files="${front_end_files} /var/www/${filename}"
were you able to determine why you have to do this on that repository? I'm worried about how it's going to effect the rest of them. This would also lock all files into being in the /var/www/ directory instead of using a relative path.

2020-10-15 19:32 UTC, aserv92 commented on bin/style-fixer
> +    front_end_files="${front_end_files} /var/www/${filename}"
Yea it turns out it just fine without this change.

2020-10-16 15:03 UTC, BKorenek approved these changes

2020-10-16 15:12 UTC, merged