Add Java Style Fixer
Medology/submodules pull request #47
Opened 2020-11-24 02:34 UTC by juanmrad

## Issue:
As we work more with qa repos we want to have a central place where we store bin commands to keep all projects standardized and using the same style fixer and scripts.

## Solution:
Create a  java-styler bin file.
add java styler to the images file.
Include java files as a check for modified files on ci fixer
Add Java fixer to the fixer script

2020-11-24 17:11 UTC, rashidsaf approved these changes

2020-11-25 14:59 UTC, Chekote requested changes

2020-11-25 14:59 UTC, Chekote commented on bin/java-styler
> +    ${LOCAL_USER_ID:-} \
The image does not support this env var. Only images based on my images support this.

You need to implement a solution to prevent the container from running as root. Since you aren't extending my base images, this will occur with or without this line.

2020-11-25 14:59 UTC, Chekote commented on bin/java-styler
> +    -w /workdir \
You should set this as the default workdir in your base image so you don't need to change it here.

2020-11-25 14:59 UTC, Chekote commented on bin/java-styler
> +    -v $(pwd):/workdir:delegated \
This would work better if we could leverage the volumes that we're using as standard now. The submodules seem to be looking for a list of volumes in `/docker/lib/volumes.sh`. If we set that up in the project where you want to use this you can leverage that here.

e.g. if we did it on STDcheck, the `/docker/lib/volumes.sh` would look like:

```shell
# Associative array mapping Docker Volume names to paths
declare -A VOLUMES
VOLUMES["user_cache"]="$HOME/.cache"
VOLUMES["user_composer"]="$HOME/.composer"
VOLUMES["user_gitconfig"]="$HOME/.gitconfig"
VOLUMES["user_ssh"]="$HOME/.ssh"
VOLUMES["user_wrangler"]="$HOME/.wrangler"
VOLUMES["stdcheck_project"]="$ROOT"
VOLUMES["stdcheck_logs"]="$ROOT/storage/logs"
```

Since this is a generic style fixer, and not coupled to any specific project, we can't couple it to the `stdcheck_project` volume. So instead, we should add an alias to this (and all other projects that we set this up in) for the general project volume:

```shell
# Associative array mapping Docker Volume names to paths
declare -A VOLUMES
VOLUMES["user_cache"]="$HOME/.cache"
VOLUMES["user_composer"]="$HOME/.composer"
VOLUMES["user_gitconfig"]="$HOME/.gitconfig"
VOLUMES["user_ssh"]="$HOME/.ssh"
VOLUMES["user_wrangler"]="$HOME/.wrangler"
VOLUMES["stdcheck_project"]="$ROOT"
VOLUMES["stdcheck_logs"]="$ROOT/storage/logs"

PROJECT_VOLUME="stdcheck_project"
```

Then when you pull in ``/docker/lib/volumes.sh` in this file, you can utilize that:

```
docker run $TTY --rm -i --mount source=$PROJECT_VOLUME,target=/workdir $JAVA_STYLER_IMAGE "$@"
```

2020-11-25 14:59 UTC, Chekote commented on bin/java-styler
> +    ${TTY} \
Curly braces have no effect here. Please remove them.

2020-11-25 14:59 UTC, Chekote commented on bin/java-styler
> +    ${JAVA_STYLER_IMAGE} "$@"
Curly braces have no effect here. Please remove them.

2020-11-25 14:59 UTC, Chekote commented on bin/get_images
> +export JAVA_STYLER_IMAGE=${GCR_US_HOST}/${GOOGLE_PROJECT_ID}/${JAVA_STYLER_REPO}:${JAVA_STYLER_TAG}
Curly braces have no effect here. Please remove them.

2020-11-25 14:59 UTC, Chekote commented on bin/style-fixer
> +  echo ${java_files}
Curly braces have no effect here. Please remove them.

2020-11-25 14:59 UTC, Chekote commented on bin/style-fixer
> +  echo -e "${GREEN}Fixing Java files code style...${NC}"
Curly braces are needed for the first var here because it is butting up against the "Fixing" word. But not for the NC var.

```suggestion
  echo -e "${GREEN}Fixing Java files code style...$NC"
```

2020-11-25 14:59 UTC, Chekote commented on bin/style-fixer
> +    java_files="${java_files} ${filename}"
Curly braces have no effect here. Please remove them.

2020-11-26 01:30 UTC, juanmrad commented on bin/java-styler
> +    -v $(pwd):/workdir:delegated \
I wanted to do something like this, but wasn't sure how to implement it. I had done this on Raven to where all scripts would mount the volumes over instead, but wasn't sure on how to do it with the submodules

2020-11-26 02:49 UTC, juanmrad commented on bin/java-styler
> +    ${LOCAL_USER_ID:-} \
I've gone ahead and modified the image to have su-exec and allow to have this environment variable so it is more in line with all our other docker images

2020-11-26 02:49 UTC, juanmrad commented on bin/get_images
> +export JAVA_STYLER_IMAGE=${GCR_US_HOST}/${GOOGLE_PROJECT_ID}/${JAVA_STYLER_REPO}:${JAVA_STYLER_TAG}
went ahead and removed them for all lines on this file.

2020-11-26 02:49 UTC, juanmrad commented on bin/style-fixer
> +  echo ${java_files}
went ahead and removed them for all lines on this file.

2020-11-30 22:04 UTC, BKorenek approved these changes

2020-12-01 15:22 UTC, Chekote approved these changes

2020-12-01 15:51 UTC, merged