Fix set -o and remove gsed since colored output is disabled in composer 2.0
Medology/submodules pull request #49
Opened 2020-12-17 19:44 UTC by johnnie502

For https://github.com/Medology/www.healthlabs.com/issues/1400

This PR will fix the following for `install_composer` script
* `set -euo -pipefail` should be `set -eu -o pipfail`
* `gsed` is not needed anymore since composer output has no color since 2.0

2020-12-17 19:47 UTC, manuerumx approved these changes

2020-12-17 23:59 UTC, jose-ochoa requested changes

2020-12-17 23:59 UTC, jose-ochoa commented on bin/install_composer
> +set -eu -o pipefail
Why not `-euo pipefail` ?

2020-12-18 15:22 UTC, johnnie502 commented on bin/install_composer
> +set -eu -o pipefail
Getting this error on Macos

<img width="550" alt="Screen Shot 2020-12-18 at 9 22 05 AM" src="https://user-images.githubusercontent.com/1442600/102630757-8e723c00-4112-11eb-9a32-d20ba10aa048.png">

2020-12-18 15:29 UTC, jose-ochoa approved these changes

2020-12-18 15:32 UTC, Chekote approved these changes
No color?!?! So much for an "upgrade" 😿

2020-12-18 15:33 UTC, merged