Add init_npmrc script to initialize .npmrc file
Medology/submodules pull request #52
Opened 2021-02-16 23:27 UTC by izazueta

For Medology/my-account#183

## Description
* Add `init_npmrc` script to initialize an `.npmrc` file required to work with private NPM packages.

2021-02-17 02:26 UTC, manuerumx approved these changes

2021-02-18 12:18 UTC, rashidsaf requested changes

2021-02-18 12:18 UTC, rashidsaf commented on bin/init_npmrc
> +  sed -i "s/TOKEN/$NPM_TOKEN/" "$ROOT"/.npmrc
This command will fail on Mac. `sed` for OSX and Linux are not exactly the same. Below should work both. Please try this for both OSX and Linux also `zsh` and `bash` before the change
```suggestion
  sed -i'' -e "s/TOKEN/$NPM_TOKEN/" "$ROOT"/.npmrc
```

2021-02-18 18:25 UTC, izazueta commented on bin/init_npmrc
> +  sed -i "s/TOKEN/$NPM_TOKEN/" "$ROOT"/.npmrc
Thanks for the catch, I ended detecting the OS and executing different commands because using `sed -i'' -e...` works but creates a duplicated file named `.npmrc-e` on mac.

2021-02-18 18:49 UTC, rashidsaf approved these changes

2021-02-19 14:57 UTC, merged