Add stop_previous_versions to the gcloud lib
Medology/submodules pull request #63
Opened 2021-05-26 17:27 UTC by johnnie502

As title says, this PR add the script

2021-05-26 21:05 UTC, BKorenek requested changes

2021-05-26 21:05 UTC, BKorenek commented on lib/gcloud.sh
> +    ids=$(gcloud app versions list --service default \
```suggestion
    local ids=$(gcloud app versions list --service default \
```

2021-05-26 21:05 UTC, BKorenek commented on lib/gcloud.sh
> +    ids=$(gcloud app versions list --service default \
Aren't we supposed to wrap these guys in double quotes so there's no chance of lines being messed up?

2021-05-26 21:05 UTC, BKorenek commented on lib/gcloud.sh
> +    echo -e "\nStopping all previous serving versions of $1"
We should establish a local variable for the argument 
`local service="$1"` so it can be used here and in the end of method.

2021-05-26 21:05 UTC, BKorenek commented on lib/gcloud.sh
> +    echo -e "\nStopping all previous serving versions of $1"
Is this echo entirely necessary? Aren't we echoing before each version as is?

2021-05-27 13:17 UTC, Chekote commented on lib/gcloud.sh
> +    echo -e "\nStopping all previous serving versions of $1"
It's necessary because if there are no versions to stop, this will be the only output.

2021-05-27 13:20 UTC, Chekote requested changes

2021-05-27 13:20 UTC, Chekote commented on lib/gcloud.sh
> +    ids=$(gcloud app versions list --service default \
It seems you forgot to use the service parameter and are hard-coding `default` instead.

2021-05-27 13:27 UTC, Chekote approved these changes

2021-05-27 15:10 UTC, BKorenek commented on lib/gcloud.sh
> +    echo -e "\nStopping all previous serving versions of $1"
seems implicit ;)

2021-05-27 15:11 UTC, BKorenek approved these changes

2021-05-27 15:13 UTC, Chekote commented on lib/gcloud.sh
> +    echo -e "\nStopping all previous serving versions of $1"
It's a question of verbosity. Should you only state what you are attempting to do, or what you succeed in doing.

2021-05-27 16:24 UTC, merged