updating GITHUB_OAUTH env var
Medology/submodules pull request #64
Opened 2021-05-27 20:16 UTC by DevanTarunKumar

For: https://github.com/Medology/stdcheck.com/issues/12697

Updating the GITHUB_OAUTH env var to GITHUB_READ_OAUTH to align with changes made with respect to least privilege policy on stdcheck

2021-05-27 20:24 UTC, manuerumx approved these changes

2021-05-28 14:39 UTC, Chekote requested changes

2021-05-28 14:39 UTC, Chekote commented on bin/ci-style-fixer
> +    echo $(curl -H "Authorization: token $GITHUB_READ_OAUTH" -H "Accept: application/vnd.github.shadow-cat-preview+json" \
I recommend you use a backward-compatible approach here as to not break other projects.

Please mark the `GITHUB_OAUTH` as deprecated and notify all teams that they should migrate away from using it.

```suggestion
    echo $(curl -H "Authorization: token ${GITHUB_READ_OAUTH:-$GITHUB_OAUTH}" -H "Accept: application/vnd.github.shadow-cat-preview+json" \
```

2021-06-02 12:26 UTC, DevanTarunKumar commented
Changed it from `GITHUB_READ_OAUTH` to `GITHUB_WRITE_OAUTH` as it writes changes to the code after making code style changes

2021-06-02 13:03 UTC, Chekote requested changes
> Changed it from `GITHUB_READ_OAUTH` to `GITHUB_WRITE_OAUTH` as it writes changes to the code after making code style changes

That's not true. The method is called `get_pr_details`. All it does is read data from Github. This env var is used in this single curl request. This is not a method to authenticate in general.

I think you are confusing this method with something else.

2021-06-02 13:04 UTC, Chekote requested changes

2021-06-02 13:04 UTC, Chekote commented on bin/ci-style-fixer
> +    echo $(curl -H "Authorization: token ${GITHUB_WRITE_OAUTH:-$GITHUB_OAUTH}" -H "Accept: application/vnd.github.shadow-cat-preview+json" \
Falling back to the write token if the read is not available is fine. But you should not require the write if the read is available, as this is a read only operation.

2021-06-02 14:41 UTC, Chekote approved these changes

2021-06-02 14:41 UTC, Chekote commented on bin/ci-style-fixer
> +    echo $(curl -H "Authorization: token ${GITHUB_READ_OAUTH:-$GITHUB_OAUTH}" -H "Accept: application/vnd.github.shadow-cat-preview+json" \
This is not doing what I said in my [previous comment](https://github.com/Medology/submodules/pull/64#discussion_r643941107). But we can go with this for now and add support for falling back to the write access if neither generic or read keys are available later. Hopefully, you don't need that in your other PR otherwise you'll end up having to submit another PR here to fix it yourself.

2021-06-09 20:28 UTC, merged