Composer install script
Medology/submodules pull request #66
Opened 2021-07-02 14:13 UTC by manuerumx

For: #something

BUG FIX:

**Cause:**

**Solution:**

FEATURE IMPLEMENTATION:

Whatever you want (screenshots, etc)

2021-07-02 20:13 UTC, jose-ochoa requested changes

2021-07-02 20:13 UTC, jose-ochoa commented on bin/init/install-composer.sh
> +#   "composer: OK" when the validation pass otherwise will return different type of errors
please update the return description to reflect the 1/0 status code

2021-07-02 20:13 UTC, jose-ochoa commented on bin/init/install-composer.sh
> +  curl -L https://getcomposer.org/download/${EXPECTED_VERSION}/composer.phar.sha256sum > "$ROOT"/bin/composer.sha256sum
I don't think we should download the SHA, we should hard code it like the expected version. And check it against the download file. If they were to overwrite the file and update the SHA we wouldn't know

2021-07-02 22:44 UTC, manuerumx commented on bin/init/install-composer.sh
> +  curl -L https://getcomposer.org/download/${EXPECTED_VERSION}/composer.phar.sha256sum > "$ROOT"/bin/composer.sha256sum
I don't see why the SHA could change unless it's a different file and most likely, a new version.

What you suggest is the way we check the composer installation. So far I'm not aware of the behavior you are worried about ever happening before. 

If the composer organization changes the file and the SHA, but the changes are published with the same version, the PHP community has a bigger problem.

I think the idea of these validations is to ensure the downloaded file is not corrupted by a problem during its download.

Next week, we can discuss this with the team.

2021-07-03 01:33 UTC, jose-ochoa commented on bin/init/install-composer.sh
> +  curl -L https://getcomposer.org/download/${EXPECTED_VERSION}/composer.phar.sha256sum > "$ROOT"/bin/composer.sha256sum
Verifying against a known SHA and explicitly comparing them is the only guarantee we can have, it's like the composer.lock file equivalent. But I'll comply with whatever outcome is.

2021-07-06 10:41 UTC, rashidsaf commented on bin/init/install-composer.sh
> +  curl -L https://getcomposer.org/download/${EXPECTED_VERSION}/composer.phar.sha256sum > "$ROOT"/bin/composer.sha256sum
The chance of this happening is highly unlikely.

2021-07-06 10:44 UTC, rashidsaf approved these changes

2021-07-06 14:43 UTC, manuerumx commented
Are you ok with the changes @jose-ochoa

2021-07-06 15:17 UTC, jose-ochoa requested changes

2021-07-06 15:17 UTC, jose-ochoa commented on bin/init/install-composer.sh
> +#s
Please remove cmd + `s`

2021-07-06 15:20 UTC, jose-ochoa commented on bin/init/install-composer.sh
> +  curl -L https://getcomposer.org/download/${EXPECTED_VERSION}/composer.phar.sha256sum > "$ROOT"/bin/composer.sha256sum
![image](https://user-images.githubusercontent.com/16085034/124625514-7e6a4180-de43-11eb-830f-dbb1bbe43c88.png)

2021-07-06 15:22 UTC, jose-ochoa approved these changes

2021-07-06 15:33 UTC, merged