Extract libraries from ci-style-fixer
Medology/submodules pull request #71
Opened 2021-08-04 17:39 UTC by Chekote

## Problem
There are functions within the ci-style-fixer that can be used by other scripts either in submodules or the host projects that need to work with Github, CircleCI, Git etc. Since these functions are within the ci-style-fixer script, it is not possible to utilize them from other scripts.

## Fix
Extract the functions into bash library scripts within the `lib` folder so that they can be re-used.

2021-08-04 17:56 UTC, manuerumx requested changes
Just a question about the implementation

2021-08-04 17:56 UTC, manuerumx commented on lib/github.sh
> +github::pull::url::get () {
Can you explain to me why is defined with colons, but is invoked using only a dot?

Definition: `github::pull::url::get`
Invocation: `git_url=$(github.pull.url.get "$api_response")`

To be consistent shouldn't be declared with dots like in the git.sh file?

2021-08-04 19:26 UTC, Chekote commented on lib/github.sh
> +github::pull::url::get () {
Yes, I missed this one when I changed from :: to . in the final commit. I will fix it.

2021-08-04 20:47 UTC, manuerumx approved these changes

2021-08-05 11:51 UTC, rashidsaf approved these changes

2021-08-05 11:51 UTC, rashidsaf commented on lib/github.sh
> +      local OAUTH=$GITHUB_OAUTH
I think we should also validate if `GITHUB_OAUTH` exists or not

2021-08-05 11:52 UTC, rashidsaf approved these changes

2021-08-05 13:08 UTC, DevanTarunKumar approved these changes

2021-08-05 15:24 UTC, Chekote commented on lib/github.sh
> +      local OAUTH=$GITHUB_OAUTH
I'm going to be making a change to the way CircleCI contexts works whereby $GITHUB_OAUTH will be the only token. Doing so will simplify the checks by removing the necessity for these if statements. When I do that, I'll also add a check to ensure it exists.

2021-08-05 15:25 UTC, merged