[DO NOT REVIEW] Various cleanup
Medology/submodules pull request #85
Opened 2021-11-02 14:43 UTC by Chekote

2021-11-05 00:49 UTC, jose-ochoa approved these changes

2021-11-05 15:28 UTC, BKorenek requested changes

2021-11-05 15:28 UTC, BKorenek commented on lib/docker_network.sh
> +readonly DOCKER_NETWORK=global
the previous convention I've been using for things that retrieve variables is `get_docker_network` for naming. Not sure if we want to have a conversation on that and/or set something in stone?

2021-11-05 15:28 UTC, BKorenek commented on bin/gsed
> +alpine-container sed "$@"
What's the g in gsed mean?

Could we not simply call this one liner instead of creating an entire binary? feels a little overkill

2021-11-05 15:28 UTC, BKorenek commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
Same for this here, could we not just call this where we need to?

2021-11-05 15:28 UTC, BKorenek commented on bin/gsutil
> +gcloud-sdk-container gsutil "$@"
Same for this here, could we not just call this where we need to?

2021-11-05 15:28 UTC, BKorenek commented on bin/init/install_composer.sh
> +  local PARSED_SHA256_SUM
Not sure if you deem this as in scope or not, but capitalization generally means const and in bash implies global. so this next to a local declaration is hurting me

2021-11-05 15:28 UTC, BKorenek commented on bin/generate_ide_helper.sh
> +#!/usr/bin/env bash
Didn't we have namespaced function libraries we could nest this in?

2021-11-05 15:30 UTC, Chekote commented on lib/docker_network.sh
> +readonly DOCKER_NETWORK=global
Yeah, we did have that discussion. But this is an environmental variable, not a local variable. You can tell because it is exported at the end of the script. So since it's an env var, it should be all caps.

2021-11-05 15:32 UTC, Chekote commented on bin/gsed
> +alpine-container sed "$@"
g stands for GNU. BSD sed and GNU sed behave differently. If you want to use the same sed command across different operating systems and have it behave the same, you need to use a specific distro's sed.

2021-11-05 15:35 UTC, Chekote commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
You could, but then that would defeat our philosophy of having Docker be transparent and act as if it was a native CLI command. If I can no longer type `gcloud` on the command line as Google's documentation would instruct me to, and I have to know about this proprietary `gcloud-sdk-container gcloud` command, then that's an additional cognitive overhead that developers would need to deal with before they can become proficient in the usage of this project.

Additionally, any script that wants to use `gcloud` would somehow need to also know about this proprietary way of calling `gcloud`. With this script in place, and the containing dir as part of the system PATH, it ensures that all scripts and commands will use this specific `gcloud`, thus insulating the project and the user from discrepancies across environments due to different `gcloud` versions being installed.

2021-11-05 15:36 UTC, Chekote commented on bin/init/install_composer.sh
> +  local PARSED_SHA256_SUM
This is fixed in a later commit.

2021-11-05 15:37 UTC, Chekote commented on bin/generate_ide_helper.sh
> +#!/usr/bin/env bash
I do not understand what you are asking me to do. We have bash libraries for git, circleci, etc. But I do not understand how those are related to this file.

2021-11-05 15:37 UTC, Chekote commented on bin/gsutil
> +gcloud-sdk-container gsutil "$@"
Please see my comment above.

2021-11-05 17:54 UTC, BKorenek requested changes
I replied to your comments

2021-11-05 17:54 UTC, BKorenek commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
so, gcloud sdk container should probably just be named to gcloud and then add the arguments to the script itself right?

2021-11-05 17:54 UTC, BKorenek commented on bin/generate_ide_helper.sh
> +#!/usr/bin/env bash
well i was thinking we should move it into a function and create a library import for it, but I guess this one is probably pretty one off

2021-11-05 17:54 UTC, BKorenek commented on lib/docker_network.sh
> +readonly DOCKER_NETWORK=global
im referencing the name of the file itself

2021-11-05 17:58 UTC, Chekote commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
That's not possible, because there is both a `gcloud` and a `gsutil` command that both use the `google-sdk-container`.

2021-11-05 18:03 UTC, BKorenek commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
Isn't that a violation of SRP though? is gsutil a part of the gcloud cli package?

2021-11-05 18:04 UTC, Chekote commented on lib/docker_network.sh
> +readonly DOCKER_NETWORK=global
OK, sure, I can make that change.

2021-11-05 18:06 UTC, BKorenek approved these changes

2021-11-05 18:12 UTC, Chekote commented on bin/gcloud
> +gcloud-sdk-container gcloud "$@"
Both the `gcloud` and `gsutil` commands are part of the Google Cloud SDK.

[This is my Dockerfile that installs the Google Cloud SDK](https://github.com/Chekote/docker-google-cloud-sdk/blob/main/Dockerfile) that that image is using. As you can see I am only installing Python and the Google Cloud SDK, so they are definitely not separate.

2021-11-08 12:43 UTC, rashidsaf approved these changes

2021-11-08 12:59 UTC, merged