Re-write if condition to avoid duplicated output
Medology/submodules pull request #87
Opened 2021-11-19 23:15 UTC by aserv92

For: Medology/stdcheck-wp-theme/issues/313

This PR is to fix an issue with fixable files being processed twice.

2021-11-29 03:39 UTC, jose-ochoa requested changes

2021-11-29 03:39 UTC, jose-ochoa commented on bin/ci-style-fixer
> +      if `echo "$file" | grep -q 'css\|scss\|html\|js\|ts\|php\|java\|feature\|twig'`; then
`Remove backticks to avoid executing output.` per https://github.com/koalaman/shellcheck/wiki/SC2092

2021-11-29 12:22 UTC, rashidsaf requested changes
.

2021-11-29 19:54 UTC, jose-ochoa approved these changes

2021-11-30 12:23 UTC, rashidsaf approved these changes

2021-12-01 15:57 UTC, merged